### ISSUE TITLE
emerge cachyos-sources 6.6.0 failed

### ISSUE THREAD

**Issue by xz-dev** [Szowisz/CachyOS-kernels#10]
Command: `genkernel --menuconfig all`
Default config

Log: `ERROR: Something went wrong: Required kernel option 'CONFIG_MICROCODE_AMD' which genkernel tried to set is missing!`
Log file: [genkernel.log](https://github.com/Szowisz/CachyOS-kernels/files/13225611/genkernel.log)

**Comment by Szowisz** [comment]
https://forums.gentoo.org/viewtopic-p-8806020.html?sid=352b27a1b0b5eb4ed4106883703011e1
https://bugs.gentoo.org/914445
Similar problems.
The issue is not related to Cachy kernel, but to genkernel itself

**Comment by Szowisz** [comment]
Edit /etc/genkernel.conf and add OLDCONFIG="no". From what I'm reading it fixes this problem.
