### ISSUE TITLE
How to enable LLVM LTO

### ISSUE THREAD

**Issue by xz-dev** [Szowisz/CachyOS-kernels#11]
I use `make menuconfig LLVM=1 KCFLAGS='-O3 -march=native -pipe' -j$(( $(nproc) + 1 ))` to build kernel with LTO(full or thin), but it got a error:
```
  AR      kernel/built-in.a
  STUBCPY drivers/firmware/efi/libstub/randomalloc.stub.o
  STUBCPY drivers/firmware/efi/libstub/relocate.stub.o
  STUBCPY drivers/firmware/efi/libstub/secureboot.stub.o
  STUBCPY drivers/firmware/efi/libstub/skip_spaces.stub.o
  STUBCPY drivers/firmware/efi/libstub/tpm.stub.o
  STUBCPY drivers/firmware/efi/libstub/unaccepted_memory.stub.o
  STUBCPY drivers/firmware/efi/libstub/vsprintf.stub.o
  STUBCPY drivers/firmware/efi/libstub/x86-5lvl.stub.o
  STUBCPY drivers/firmware/efi/libstub/x86-stub.stub.o
  STUBCPY drivers/firmware/efi/libstub/bitmap.stub.o
  AR      drivers/firmware/efi/libstub/lib.a
  AR      drivers/firmware/built-in.a
  AR      drivers/built-in.a
  CC      arch/x86/kernel/cpu/capflags.o
  AR      arch/x86/kernel/cpu/built-in.a
  AR      arch/x86/kernel/built-in.a
  AR      arch/x86/built-in.a
  AR      built-in.a
  AR      vmlinux.a
  GEN     .tmp_initcalls.lds
scripts/generate_initcall_order.pl: ERROR: no initcalls? at scripts/generate_initcall_order.pl line 243.
make[2]: *** [scripts/Makefile.vmlinux_o:22: .tmp_initcalls.lds] Error 10
make[2]: *** Deleting file '.tmp_initcalls.lds'
make[1]: *** [/usr/src/linux-6.6.6-cachyos/Makefile:1149: vmlinux_o] Error 2
make: *** [Makefile:234: __sub-make] Error 2

* ERROR: compile_kernel(): compile_generic() failed to compile the "bzImage" target!
* Please consult '/var/log/genkernel.log' for more information and any
* errors that were reported above.

```
I had checked the LTO config is same as [linux-cachyos PKGBUILD](https://github.com/CachyOS/linux-cachyos/blob/c67e699dccd623b5c30515486a4f3c7234dfc1df/linux-cachyos/PKGBUILD#L331C14-L331C14)

**Comment by acjones8** [comment]
The exact command that I use to configure for LTO Clang is: `sudo make LLVM=1 LLVM_IAS=1 menuconfig`, and I've not had any problems with it. Have you gotten LTO to work in the past, or is this the first time you're seeing these build errors?

**Comment by xz-dev** [comment]
I had try again by manually use `make` command, but not through `genkernel`, it's all right.
And I had check my `genkernel.conf` again, find I had enable `ccache clang` as buildchain, I had try `ccache -C` to clean cache and rebuild via genkernel again, and it failed. But if I use clang but not ccache clang as my buildchain, it also will working fine.
So I think, It's a bug of ccache clang, it's not CachyOS-kernels's problem.

**Comment by xz-dev** [comment]
Update: my `genkernel` config is wrong, my bad, I should not set ccache to `as` `ar` `ld` etc
