### ISSUE TITLE
During the installation, portage prompts not to find PT_DYNAMIC

### ISSUE THREAD

**Issue by qwe795138426** [Szowisz/CachyOS-kernels#16]
0001-bore-cachy-rt.patch can't patch properly on sys-kernel/cachyos-sources-6.11.2+
`>>> Emerging (1 of 1) sys-kernel/cachyos-sources-6.11.3::CachyOS-kernels
 * linux-6.11.tar.xz BLAKE2B SHA512 size ;-) ...                                                                                                                                       [ ok ]
 * genpatches-6.11-4.base.tar.xz BLAKE2B SHA512 size ;-) ...                                                                                                                           [ ok ]
 * genpatches-6.11-4.extras.tar.xz BLAKE2B SHA512 size ;-) ...                                                                                                                         [ ok ]
 * >>> Preparing to unpack ...
>>> Unpacking source...
>>> Unpacking linux-6.11.tar.xz to /var/tmp/portage/sys-kernel/cachyos-sources-6.11.3/work
>>> Unpacking genpatches-6.11-4.base.tar.xz to /var/tmp/portage/sys-kernel/cachyos-sources-6.11.3/work/patches
clang-cpp: warning: argument unused during compilation: '-E' [-Wunused-command-line-argument]
clang-cpp: warning: argument unused during compilation: '-E' [-Wunused-command-line-argument]
clang-cpp: warning: argument unused during compilation: '-E' [-Wunused-command-line-argument]
>>> Unpacking genpatches-6.11-4.extras.tar.xz to /var/tmp/portage/sys-kernel/cachyos-sources-6.11.3/work/patches
clang-cpp: warning: argument unused during compilation: '-E' [-Wunused-command-line-argument]
clang-cpp: warning: argument unused during compilation: '-E' [-Wunused-command-line-argument]
clang-cpp: warning: argument unused during compilation: '-E' [-Wunused-command-line-argument]
 * Excluding Patch #5010_enable-additional-cpu-optimizations-for-gcc.patch ...                                                                                                         [ ok ]
 * Excluding Patch #5010_enable-additional-cpu-optimizations-for-gcc-4.9.patch ...                                                                                                     [ ok ]
 * Excluding Patch #5011_enable-cpu-optimizations-for-gcc8.patch ...                                                                                                                   [ ok ]
 * Excluding Patch #5012_enable-cpu-optimizations-for-gcc91.patch ...                                                                                                                  [ ok ]
 * Excluding Patch #5013_enable-cpu-optimizations-for-gcc10.patch ...                                                                                                                  [ ok ]
 * Excluding Patch #5010_enable-additional-cpu-optimizations-for-gcc.patch ...                                                                                                         [ ok ]
 * Excluding Patch #5010_enable-additional-cpu-optimizations-for-gcc-4.9.patch ...                                                                                                     [ ok ]
 * Excluding Patch #5011_enable-cpu-optimizations-for-gcc8.patch ...                                                                                                                   [ ok ]
 * Excluding Patch #5012_enable-cpu-optimizations-for-gcc91.patch ...                                                                                                                  [ ok ]
 * Excluding Patch #5013_enable-cpu-optimizations-for-gcc10.patch ...                                                                                                                  [ ok ]
 * Applying 1000_linux-6.11.1.patch (-p1) ...                                                                                                                                          [ ok ]
 * Applying 1001_linux-6.11.2.patch (-p1) ...                                                                                                                                          [ ok ]
 * Applying 1002_linux-6.11.3.patch (-p1) ...                                                                                                                                          [ ok ]
 * Applying 1510_fs-enable-link-security-restrictions-by-default.patch (-p1) ...                                                                                                       [ ok ]
 * Applying 1700_sparc-address-warray-bound-warnings.patch (-p1) ...                                                                                                                   [ ok ]
 * Applying 1730_parisc-Disable-prctl.patch (-p1) ...                                                                                                                                  [ ok ]
 * Applying 2000_BT-Check-key-sizes-only-if-Secure-Simple-Pairing-enabled.patch (-p1) ...                                                                                              [ ok ]
 * Applying 2900_tmp513-Fix-build-issue-by-selecting-CONFIG_REG.patch (-p1) ...                                                                                                        [ ok ]
 * Applying 2901_tools-lib-subcmd-compile-fix.patch (-p1) ...                                                                                                                          [ ok ]
 * Applying 2910_bfp-mark-get-entry-ip-as--maybe-unused.patch (-p1) ...                                                                                                                [ ok ]
 * Applying 2920_sign-file-patch-for-libressl.patch (-p1) ...                                                                                                                          [ ok ]
 * Applying 2990_libbpf-v2-workaround-Wmaybe-uninitialized-false-pos.patch (-p1) ...                                                                                                   [ ok ]
 * Applying 2991_libbpf-workaround-Wmaybe-uninitialized-false-pos.patch (-p1) ...                                                                                                      [ ok ]
 * Applying 2995_dtrace-6.11_p1.patch (-p1) ...                                                                                                                                        [ ok ]
 * Applying 3000_Support-printing-firmware-info.patch (-p1) ...                                                                                                                        [ ok ]
 * Applying 4567_distro-Gentoo-Kconfig.patch (-p1) ...                                                                                                                                 [ ok ]
>>> Source unpacked in /var/tmp/portage/sys-kernel/cachyos-sources-6.11.3/work
>>> Preparing source in /var/tmp/portage/sys-kernel/cachyos-sources-6.11.3/work/linux-6.11.3-cachyos-6.11.3 ...
 * Applying 0001-cachyos-base-all.patch ...                                                                                                                                            [ ok ]
 * Applying 0001-rt.patch ...
patching file arch/arm/Kconfig
patching file arch/arm/mm/fault.c
patching file arch/arm/vfp/vfpmodule.c
patching file arch/arm64/Kconfig
patching file arch/powerpc/Kconfig
patching file arch/powerpc/include/asm/stackprotector.h
patching file arch/powerpc/kernel/traps.c
patching file arch/powerpc/kvm/Kconfig
patching file arch/powerpc/platforms/pseries/Kconfig
patching file arch/powerpc/platforms/pseries/iommu.c
patching file arch/riscv/Kconfig
patching file arch/riscv/include/asm/thread_info.h
Hunk #1 succeeded at 100 (offset 5 lines).
Hunk #2 succeeded at 111 (offset 5 lines).
patching file arch/x86/Kconfig
patching file arch/x86/include/asm/thread_info.h
patching file drivers/acpi/processor_idle.c
patching file drivers/block/zram/zram_drv.c
patching file drivers/block/zram/zram_drv.h
patching file drivers/gpu/drm/i915/Kconfig
patching file drivers/gpu/drm/i915/display/intel_crtc.c
patching file drivers/gpu/drm/i915/display/intel_cursor.c
patching file drivers/gpu/drm/i915/display/intel_display_trace.h
patching file drivers/gpu/drm/i915/display/intel_vblank.c
patching file drivers/gpu/drm/i915/gt/intel_execlists_submission.c
patching file drivers/gpu/drm/i915/gt/uc/intel_guc.h
patching file drivers/gpu/drm/i915/i915_request.c
patching file drivers/gpu/drm/i915/i915_trace.h
patching file drivers/gpu/drm/i915/i915_utils.h
patching file drivers/tty/serial/8250/8250_core.c
patching file drivers/tty/serial/8250/8250_port.c
patching file drivers/tty/serial/amba-pl011.c
patching file drivers/tty/serial/serial_core.c
patching file drivers/tty/tty_io.c
patching file fs/proc/consoles.c
patching file include/linux/bottom_half.h
patching file include/linux/console.h
patching file include/linux/entry-common.h
patching file include/linux/entry-kvm.h
patching file include/linux/interrupt.h
patching file include/linux/printk.h
patching file include/linux/rwlock_rt.h
patching file include/linux/sched.h
Hunk #1 succeeded at 1816 (offset 2 lines).
Hunk #2 succeeded at 1959 (offset 2 lines).
Hunk #3 succeeded at 1982 (offset 2 lines).
Hunk #4 succeeded at 2086 (offset 2 lines).
patching file include/linux/sched/idle.h
patching file include/linux/serial_8250.h
patching file include/linux/serial_core.h
patching file include/linux/spinlock_rt.h
patching file include/linux/thread_info.h
patching file include/linux/trace_events.h
patching file kernel/Kconfig.preempt
patching file kernel/entry/common.c
patching file kernel/entry/kvm.c
patching file kernel/ksysfs.c
patching file kernel/locking/lockdep.c
patching file kernel/locking/rtmutex.c
patching file kernel/locking/spinlock_rt.c
patching file kernel/panic.c
patching file kernel/printk/internal.h
patching file kernel/printk/nbcon.c
patching file kernel/printk/printk.c
patching file kernel/printk/printk_ringbuffer.h
patching file kernel/printk/printk_safe.c
patching file kernel/rcu/rcutorture.c
patching file kernel/rcu/tree_exp.h
patching file kernel/rcu/tree_stall.h
patching file kernel/sched/core.c
Hunk #6 succeeded at 7389 (offset 7 lines).
patching file kernel/sched/debug.c
patching file kernel/sched/fair.c
patching file kernel/sched/features.h
patching file kernel/sched/idle.c
patching file kernel/sched/rt.c
patching file kernel/sched/sched.h
patching file kernel/softirq.c
patching file kernel/time/hrtimer.c
patching file kernel/time/tick-sched.c
patching file kernel/time/timer.c
patching file kernel/trace/trace.c
patching file kernel/trace/trace_output.c
patching file net/netfilter/nft_counter.c
patching file kernel/Kconfig.preempt                                                                                                                                                   [ ok ]
 * Applying 0001-bore-cachy-rt.patch ...                                                                                                                                               [ ok ]
/var/tmp/portage/sys-kernel/cachyos-sources-6.11.3/temp/environment: line 2027: PT_DYNAMIC: command not found
 * ERROR: sys-kernel/cachyos-sources-6.11.3::CachyOS-kernels failed (prepare phase):
 *   (no error message)
 * 
 * Call stack:
 *     ebuild.sh, line 136:  Called src_prepare
 *   environment, line 2027:  Called die
 * The specific snippet of code:
 *           PT_DYNAMIC -e PREEMPT_BUILD -e PREEMPT_BUILD_AUTO -e PREEMPT_AUTO || die;
 * 
 * If you need support, post the output of `emerge --info '=sys-kernel/cachyos-sources-6.11.3::CachyOS-kernels'`,
 * the complete build log and the output of `emerge -pqv '=sys-kernel/cachyos-sources-6.11.3::CachyOS-kernels'`.
 * The complete build log is located at '/var/tmp/portage/sys-kernel/cachyos-sources-6.11.3/temp/build.log'.
 * The ebuild environment file is located at '/var/tmp/portage/sys-kernel/cachyos-sources-6.11.3/temp/environment'.
 * Working directory: '/var/tmp/portage/sys-kernel/cachyos-sources-6.11.3/work/linux-6.11.3-cachyos-6.11.3'
 * S: '/var/tmp/portage/sys-kernel/cachyos-sources-6.11.3/work/linux-6.11.3-cachyos-6.11.3'
`

And I found that it can fix this problem to get back ebuild back

scripts/config -e SCHED_BORE --set-val MIN_BASE_SLICE_NS 1000000 -e PREEMPT_COUNT -e PREEMPTION -d PREEMPT_VOLUNTARY -d PREEMPT -d PREEMPT_NONE -d PREEMPT_RT -d PREEMPT_DYNAMIC -e PREEMPT_BUILD -e PREEMPT_BUILD_AUTO -e PREEMPT_AUTO || die

**Comment by xz-dev** [comment]
you are right, I will fix soon
