### ISSUE TITLE
uksmd fails to find procps

### ISSUE THREAD

**Issue by acjones8** [Szowisz/CachyOS-kernels#4]
While building uksmd, the build fails because meson doesn't detect the presence of procps, even though I verified that `sys-process/procps` is installed. I've attached the build log [here](https://pastebin.com/j08f2sTs) (sorry for the random junk characters in the output, meson refused to respect the NO_COLOR variable and setting --color n for emerge didn't help either). It fails on this line: `Run-time dependency libprocps found: NO (tried pkgconfig and cmake)`

Unless libprocps is part of a different package, perhaps the check itself is flawed?

**Comment by Szowisz** [comment]
Sorry, but I don't have clue what is wrong. For me this package compiles fine.

**Comment by acjones8** [comment]
No worries, thanks for checking! That still helps me out, since now I now it's an issue with my local setup. I'll investigate further and see if I can figure out what's going on.

**Comment by Szowisz** [comment]
Okay ;)

**Comment by acjones8** [comment]
Found the problem! I'm also subscribed to pg_overlay, and pg_overlay is using procps version 4, while base Gentoo is still using version 3. Apparently these two versions have incompatible changes, so it was causing the build check to fail. Switching to Gentoo's version was the fix.

Presumably in order to avoid conflict, pg_overlay's version of procps also installs sysctl to a different path, which affects my pull request. I'll update it to support both locations.

**Comment by Szowisz** [comment]
Great!
