### ISSUE TITLE
Pipewire needs rtkit to be installed if ananicy-cpp is activated

### ISSUE THREAD

**Issue by acjones8** [Szowisz/CachyOS-kernels#6]
This isn't a formal bug report, just a suggestion for future documentation, or a note to those running into this problem. If you run ananicy-cpp with pipewire out of the box, it will cause pipewire to crash. I did some digging and found out that I needed to install sys-auth/rtkit , presumably to assist pipewire in getting real time permissions, which Gentoo doesn't install with pipewire by default.

**Comment by Szowisz** [comment]
Okay, I added that to dependencies of ananicy-cpp ebuild.

Regards
