### ISSUE TITLE
emerge cachyos-sources 6.4.4 failed

### ISSUE THREAD

**Issue by corporal9736** [Szowisz/CachyOS-kernels#8]
When I try to emerge cachyos-sources-6.4.4, it shows
```
Missing digest for '/var/db/repos/CachyOS-kernels/sys-kernel/cachyos-sources/cachyos-sources-6.4.4.ebuild'
```
May you fix that? Many thanks!

**Comment by Szowisz** [comment]
Hello, it should be working now, and also I added cachyos-sources-6.4.5. Regards
