### ISSUE TITLE
The source of config files in sys-kernel/cachyos-kernel/files

### ISSUE THREAD

**Issue by corporal9736** [Szowisz/CachyOS-kernels#9]
I'm trying to bump cachyos-sources to 6.5, but I cannot make sure the sources of the config files. Are they from the https://github.com/CachyOS/linux-cachyos ? Or there is another upstream of these config files?

**Comment by Szowisz** [comment]
Hello. Confige and patches are taken from CachyOS github

**Comment by corporal9736** [comment]
Get that. Thanks!
